version: "3.1"
services:
   eurekaserver1:
     image: 192.168.31.107:5000/snow-server-provider:dev
     ports:
     - '20010:9090'
   eurekaserver2:
     image: 192.168.31.107:5000/snow-server-provider:dev
     ports:
     - '20011:9090'
   eurekaserver3:
     image: 192.168.31.107:5000/snow-server-provider:dev
     ports:
     - '20012:9090'
